version: "3.9"

networks:
  app-tier:
    driver: bridge

volumes:
  user_data:

services:
  user_db:
    container_name: user_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_db
    ports:
      - "5434:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
    restart: unless-stopped

  flyway_users:
    image: flyway/flyway
    container_name: flyway_users
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/conf:/flyway/conf
    env_file:
      - .env
    command: [ "migrate" ]
    depends_on:
      - user_db
